# Generated by Django 3.1.2 on 2021-04-26 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0002_mycv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycv',
            name='mycv',
            field=models.FileField(upload_to='images'),
        ),
    ]
