# Generated by Django 3.1.2 on 2021-04-26 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0003_auto_20210426_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycv',
            name='mycv',
            field=models.FileField(upload_to='static/images'),
        ),
    ]
