# Generated by Django 3.1.2 on 2021-05-06 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0004_auto_20210426_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycv',
            name='mycv',
            field=models.FileField(upload_to='static/CV/images'),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='static/CV/images'),
        ),
    ]
