# Generated by Django 3.1.2 on 2021-05-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0007_auto_20210506_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('video', models.FileField(upload_to='')),
            ],
        ),
    ]
